### ISSUE TITLE
Is the normalising constant being correctly calculated?

### ISSUE THREAD

**Issue by maxbiostat** [thomas-fung/mpcmp#10]
The implementation [here](https://github.com/thomas-fung/mpcmp/blob/main/src/utility.cpp) seems to include log(j) and not lfactorial(j) or lgamma(j + 1) in the denominator.

**Comment by thomas-fung** [comment]
Thanks for the comment. Each term in the normalising constant sum (in log-scale) can be interpreted as a sum itself:

y\log(\lambda)- \nu\log(y!) = y\log(\lambda)- \nu\Sum[\log(y)] = Sum[\log(\lambda)-\nu\log(y)].

In the now deprecated `Z` has `lgamma` in it but it gives essentially the same answer as the current `logZ` function.

``` r
mpcmp:::Z(c(2,3), 0.5, log.z = TRUE, 100)
#> Warning: 'mpcmp:::Z' is deprecated.
#> Use 'logZ' instead.
#> See help("Deprecated")
#> [1] 3.129338 5.847055
mpcmp:::logZ(c(log(2), log(3)), 0.5, 100)
#> [1] 3.129328 5.847057
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maxbiostat** [comment]
Thanks for the clarification
