### ISSUE TITLE
Post hocs

### ISSUE THREAD

**Issue by jbogomolovas2** [thomas-fung/mpcmp#16]
Hi!
First of all, this is a fantastic package! I am a biologist who deals with count data that often is not equidispersed. CMP regression using mpcmp models my data very well. The only thing that would be great to have for me and I guess other users is possibility to do posthoc or contrast comparisons. I am wondering maybe this is in your plans, or do you have a dirty script to do that/ make cmp objects communicate with emmeans or other established R packages?

**Comment by thomas-fung** [comment]
Hi @jbogomolovas2, 

I don't do much on post hocs but I am happy to look into this. We still probably start with `emmeans` and take it from there. If you think there are others that we should consider, please leave a comment here. Thanks!

**Comment by jbogomolovas2** [comment]
Dear Thomas Fung,

thank you for looking into this. Indeed I contacted emmeans developer and he suggested to start by using qdrg() function to import COMP regression model parameters for post hoc calculations. I gave a quick try and it worked, aka got results out and no errors. Will look deeper to see does it makes sense from point of view, aka does not mess up parameters and estimates internally. Maybe you could have a look at this function and check does it work with mpcmp.
