### ISSUE TITLE
offset terms in glm.cmp?

### ISSUE THREAD

**Issue by seanhardison1** [thomas-fung/mpcmp#4]
Hi Thomas,

Thanks for putting together such a helpful package. I'm interested in including an offset term in my `glm.cmp` model, but it doesn't seem to get carried through to the final output. For example,

```
set.seed(1)

#generate variable to use as an offset
cottonbolls$n_samples <- rpois(nrow(cottonbolls), 5)

#fit with offset
M.bolls <- glm.cmp(nc~ 1+stages:def+stages:def2, offset = log(n_samples),data = cottonbolls)
M.bolls$offset
```
returns a vector of zeros. Is this the correct method to incorporate an offset term into  `glm.cmp` models, or am I going about it wrong?

Best

Sean

**Comment by thomas-fung** [comment]
Hi Sean,

Thank you for that. I can confirm that's a bug. I unintentionally broke the offset function in the recent updates. Please update to the new version and that should fix the issue. 

Kind regards,
Thomas

**Comment by seanhardison1** [comment]
That solved it! Thank you.
