### ISSUE TITLE
documentation for nu estimation

### ISSUE THREAD

**Issue by seanhardison1** [thomas-fung/mpcmp#5]
Hi Thomas,

In the documentation for `glm.cmp`, the formulation for the varying dispersion model is given by 

```
Y_i ~ CMP(mu_i, nu_i)

where

E(Y_i) = mu_i = exp(x_i^T beta),

and dispersion parameters are model via

nu_i = exp(s_i^T gamma)
```

This might not warrant an issue (sorry!!), but in the formulation for for `nu_i`, what is `s_i` referring to? 

Thank you,

Sean

**Comment by thomas-fung** [comment]
Hi Sean, 

s_i is just some other covariates which may or may not be the same as x_i. 

While `glm.cmp()` doesn't allow to have a fixed or pre-specified dispersion, `glm.cmp()` allows a constant dispersion model, the model is

Y_i ~ CMP(mu_i, nu), where E(Y_i) = mu_i = exp(x_i^T beta),  

which is similar to the standard negative binomial regression model. 

Kind regards,
Thomas

**Comment by seanhardison1** [comment]
Got it. thanks so much!!
