### ISSUE TITLE
I can't generate random number from COM-POISSON distribution if mean is large

### ISSUE THREAD

**Issue by guilhermeparreira** [thomas-fung/mpcmp#6]
I know that `mpcmp::dcomp()` generates random numbers from COM-Poisson distribution. However, they fail to generate such data if mean is large.

The following example doesn't compute, or takes too much time:

```
mpcmp::rcomp(1, mu = 500, nu = 1)
```

How can I generate a COM-Poisson data with large mean efficiently?

**Comment by thomas-fung** [comment]
The current CRAN version of `mpcmp` doesn't have some of the nicer features the current development version has. The Github version should be able to generate random numbers even if the mean is large. 

``` r
mpcmp::rcomp(10, mu = 500, nu=1)
#>  [1] 514 485 503 504 478 530 498 474 511 492
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But nonetheless `rcomp()` is probably not as optimised as it can be: 
``` r
 microbenchmark::microbenchmark(mpcmp::rcomp(10, mu = 500, nu=1), times=10)
#> Unit: seconds
#>                                expr      min       lq     mean   median
#>  mpcmp::rcomp(10, mu = 500, nu = 1) 1.964895 2.013536 2.118829 2.026248
#>        uq      max neval
#>  2.039575 3.025496    10
```
<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup> 

By pre-computing some of the values, I managed to cut the time in half. 
``` r
microbenchmark::microbenchmark(mpcmp::rcomp(10, mu = 500, nu=1), times=10)
#> Unit: milliseconds
#>                                expr      min       lq     mean   median
#>  mpcmp::rcomp(10, mu = 500, nu = 1) 884.4254 894.4766 982.0907 931.3182
#>        uq      max neval
#>  959.3938 1522.566    10
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by guilhermeparreira** [comment]
Thanks Thomas!

What do you mean by "pre-computing some of the values"? Computing the random number generator for the second time?

I tried to run three times `microbenchmark::microbenchmark(mpcmp::rcomp(10, mu = 500, nu=1), times=10)` but I obtained the same computacional time...

**Comment by thomas-fung** [comment]
I just pushed a new update to Github (version 0.3.3) with some new code in `rcomp()`. You should be able to use them if you reinstall the package from Github directly or if you do a pull from the repository.

**Comment by guilhermeparreira** [comment]
OK. Thank you.
