### ISSUE TITLE
Function `comp_lambdas` not available

### ISSUE THREAD

**Issue by yangchino1** [thomas-fung/mpcmp#8]
Although the manual shows the usages of this function, it was not exported to the NAMESAPCE such that it cannot be called.

**Comment by thomas-fung** [comment]
At the moment, you can access any internal functions with call like: `mpcmp:::comp_lambdas()`. It is difficult to guess what functions end-users would end up using. Happy to more export more functions in the next update.

**Comment by thomas-fung** [comment]
Hi @yangchino1, please test out the latest version from Github. You should find most functions as part of NAMESPACE now. Thanks!
